/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as HomeLayoutImport } from './routes/_homeLayout'
import { Route as HomeLayoutIndexImport } from './routes/_homeLayout.index'
import { Route as HomeLayoutRegisterImport } from './routes/_homeLayout.register'
import { Route as ProtectedDashboardIndexImport } from './routes/_protected.dashboard.index'
import { Route as ProtectedDashboardWorkoutsImport } from './routes/_protected.dashboard.workouts'
import { Route as ProtectedDashboardProfileImport } from './routes/_protected.dashboard.profile'
import { Route as ProtectedDashboardExerciseImport } from './routes/_protected.dashboard.exercise'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutRoute = HomeLayoutImport.update({
  id: '/_homeLayout',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutIndexRoute = HomeLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutRegisterRoute = HomeLayoutRegisterImport.update({
  path: '/register',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const ProtectedDashboardIndexRoute = ProtectedDashboardIndexImport.update({
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedDashboardWorkoutsRoute = ProtectedDashboardWorkoutsImport.update(
  {
    path: '/dashboard/workouts',
    getParentRoute: () => ProtectedRoute,
  } as any,
)

const ProtectedDashboardProfileRoute = ProtectedDashboardProfileImport.update({
  path: '/dashboard/profile',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedDashboardExerciseRoute = ProtectedDashboardExerciseImport.update(
  {
    path: '/dashboard/exercise',
    getParentRoute: () => ProtectedRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_homeLayout': {
      preLoaderRoute: typeof HomeLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_homeLayout/register': {
      preLoaderRoute: typeof HomeLayoutRegisterImport
      parentRoute: typeof HomeLayoutImport
    }
    '/_homeLayout/': {
      preLoaderRoute: typeof HomeLayoutIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/_protected/dashboard/exercise': {
      preLoaderRoute: typeof ProtectedDashboardExerciseImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/dashboard/profile': {
      preLoaderRoute: typeof ProtectedDashboardProfileImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/dashboard/workouts': {
      preLoaderRoute: typeof ProtectedDashboardWorkoutsImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/dashboard/': {
      preLoaderRoute: typeof ProtectedDashboardIndexImport
      parentRoute: typeof ProtectedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  HomeLayoutRoute.addChildren([HomeLayoutRegisterRoute, HomeLayoutIndexRoute]),
  ProtectedRoute.addChildren([
    ProtectedDashboardExerciseRoute,
    ProtectedDashboardProfileRoute,
    ProtectedDashboardWorkoutsRoute,
    ProtectedDashboardIndexRoute,
  ]),
  LoginRoute,
])

/* prettier-ignore-end */
